name: Build PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-fonts-extra
    
    - name: Build PDF
      run: |
        ./scripts/build.sh
    
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: annotation-guide-pdf
        path: output/main.pdf